# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'windows-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.6'


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    python -m pip install --upgrade pip setuptools wheel
    pip install -r requirements.txt
    python setup.py bdist_egg
  displayName: 'Install dependencies'

- powershell: gci env:* | sort-object name | Format-Table -AutoSize | Out-File $env:BUILD_ARTIFACTSTAGINGDIRECTORY/environment-variables.txt

# cURL upload files
# Use cURL's supported protocols to upload files
- task: cURLUploader@2
  inputs:
    files: '**'
    #authType: 'ServiceEndpoint' # Optional. Options: serviceEndpoint, userAndPass
    serviceEndpoint: 'https://krogerhdiwasbhdistorage.blob.core.windows.net/gitcode'
    #username: # Optional
    #password: # Optional
    #url: # Required when authType == UserAndPass
    #remotePath: 'upload/$(Build.BuildId)/' # Optional
    #options: # Optional
    #redirectStderr: true # Optional
